# Generated by Django 3.2.9 on 2021-12-01 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_alter_userbankaccount_account_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneytransfer',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='account_no',
            field=models.PositiveIntegerField(default='9351984155', unique=True),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='contact',
            field=models.PositiveIntegerField(max_length=12, null=True, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
