# Generated by Django 3.2 on 2021-12-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0006_auto_20211203_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneytransfer',
            name='transaction_mode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='account_no',
            field=models.PositiveIntegerField(default='9541694242', unique=True),
        ),
    ]
