# Generated by Django 3.2.9 on 2021-12-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0005_auto_20211203_0655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneytransfer',
            old_name='from_to',
            new_name='to_account',
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='account_no',
            field=models.PositiveIntegerField(default='9346638345', unique=True),
        ),
    ]
