# Generated by Django 2.2.13 on 2021-12-22 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_auto_20171026_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='users',
            new_name='user',
        ),
    ]
